import type { CompanyFormDefinition } from "@/config/company/forms";
import { EXAMPLE_CHECK_IN_SEED } from "@/config/company/forms/example-check-in";
import { FORM_LETTERHEAD_BRAND } from "@/config/company/forms/letterhead";
import { field, type FormCategoryKey, type TemplateSeed } from "@/lib/forms/catalog";
import type { FormDocument, FormVariant } from "@/lib/forms/document";

import { FIXTURE_FORM_CATEGORIES } from "./fixture-categories";

/**
 * ============================================================================
 * TEST FIXTURE FORMS — NOT BUFF CITY SOAP FORMS
 * ============================================================================
 *
 * The shipped forms registry (`src/config/company/forms/`) holds one
 * placeholder form until Buff City Soap supplies its real catalog. The forms
 * ENGINE does far more than that one form exercises — role variants, page
 * breaks, numbered lists, expectation checklists, objective tables, policy-
 * grounded fields, narrative fields, required closings, yes/no questions read
 * back as sentences, draft appendices — so engine tests run against this
 * fixture library instead.
 *
 * Everything here is invented for tests. Every name says "Fixture"; no field,
 * option or sentence is any company's policy. A test swaps the registry in
 * with:
 *
 *   vi.mock("@/config/company/forms", async () =>
 *     (await import("@/test/forms/fixture-forms")).fixtureFormsModule(),
 *   );
 *
 * and, where it groups by category, the categories too:
 *
 *   vi.mock("@/config/company/forms/categories", async () =>
 *     (await import("@/test/forms/fixture-categories")).fixtureCategoriesModule(),
 *   );
 */

/* ------------------------------------------------------------ categories --- */

export { FIXTURE_FORM_CATEGORIES };

/** A fixture category key, typed as the catalog's key so a seed accepts it. */
const category = (key: (typeof FIXTURE_FORM_CATEGORIES)[number]["key"]) =>
  key as unknown as FormCategoryKey;

/* --------------------------------------------------------- shared parts --- */

const BRAND = FORM_LETTERHEAD_BRAND;

/** The four header fields every fixture form fills from the record. */
function header(): FormDocument["blocks"] {
  return [
    {
      kind: "field_row",
      fields: [
        field("employee_name", "Name", "system"),
        field("form_date", "Date", "system", "date"),
      ],
    },
    {
      kind: "field_row",
      fields: [
        field("job_title", "Job Title", "system"),
        field("location", "Location", "system"),
      ],
    },
  ];
}

/* ------------------------------------------------------ Fixture Coaching --- */

export const FIXTURE_COACHING_KEY = "fixture-coaching";

export const FIXTURE_COACHING_TYPES = ["Skill Building", "Refresher Training", "Recognition"];

export const FIXTURE_COACHING_TOPICS = [
  "Greeting Guests",
  "Product Demonstrations",
  "Ingredient Questions",
  "Gift Recommendations",
  "Handling Concerns",
  "Product Basics",
  "Checkout Experience",
  "Add-On Suggestions",
  "Cleaning Tasks",
  "Restocking Shelves",
  "Other",
];

export const FIXTURE_COACHING_ACKNOWLEDGEMENT =
  "I confirm that my supervisor and I have discussed this coaching and the plan for improvement.";

const slug = (label: string) =>
  label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");

/**
 * A coaching record: header, two tick groups (one with an Other write-in), one
 * drafted narrative field, an acknowledgement and two signatures. Its source
 * document is generated by `src/test/forms/source-fixtures.ts`, so the ingest
 * tests can read it back into exactly this.
 */
export function fixtureCoachingDocument(): FormDocument {
  return {
    paper: "letter",
    style: {
      headingStyle: "rule",
      letterhead: "centered",
      logo: { assetKey: "fixture-logo", placement: "top-right", widthPt: 96 },
      margins: "wide",
      signatureLayout: "ruled",
    },
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Coaching Note" },
      { kind: "section", label: "Team Member Information" },
      ...header(),
      { kind: "section", label: "Type of Coaching" },
      {
        kind: "checkbox_group",
        key: "coaching_type",
        options: FIXTURE_COACHING_TYPES.map((label) => ({ key: slug(label), label })),
        responsibility: "ai",
        columns: 3,
      },
      { kind: "section", label: "Topic of Coaching" },
      {
        kind: "checkbox_group",
        key: "coaching_topics",
        options: FIXTURE_COACHING_TOPICS.map((label) => ({ key: slug(label), label })),
        responsibility: "ai",
        columns: 3,
      },
      { kind: "field", field: field("other_topic", "Other", "ai") },
      { kind: "section", label: "Details of Coaching" },
      {
        kind: "field",
        field: field("coaching_details", "Details of Coaching", "ai", "long_text", {
          help: "Observed: what the manager saw. Expectation: what is expected. Going Forward: the agreed next step.",
          narrative: "observed_expectation",
        }),
      },
      { kind: "section", label: "Acknowledgement of Coaching" },
      { kind: "acknowledgement", text: FIXTURE_COACHING_ACKNOWLEDGEMENT },
      { kind: "signature_row", label: "Employee Signature", dateLabel: "Date" },
      { kind: "signature_row", label: "Supervisor Signature", dateLabel: "Date" },
    ],
  };
}

export const FIXTURE_COACHING_SEED: TemplateSeed = {
  key: FIXTURE_COACHING_KEY,
  name: "Fixture Coaching Note",
  shortName: "Coaching Note",
  description: "TEST FIXTURE — a coaching record for engine tests. Not a Buff City Soap form.",
  category: category("fixture-team"),
  layoutFamily: "coaching",
  requiredPermission: "create_forms",
  displayOrder: 10,
  document: fixtureCoachingDocument(),
  variants: [],
  revision: 2,
  revisionNote: "Fixture revision 2.",
  bundledPdfName: "Fixture Coaching Note.pdf",
};

/* ---------------------------------------------------- Fixture Corrective --- */

export const FIXTURE_CORRECTIVE_KEY = "fixture-corrective";

/** The sentence the fixture's action plan always ends with. Invented for tests. */
export const FIXTURE_REQUIRED_CLOSING =
  "Fixture closing line: this sentence ends every fixture action plan.";

/** The fixture's single-answer question, printed above its Yes / No boxes. */
export const FIXTURE_YES_NO_QUESTION = "Is retraining required?";

export function fixtureCorrectiveDocument(): FormDocument {
  return {
    paper: "letter",
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Corrective Notice" },
      { kind: "section", label: "Team Member Information" },
      ...header(),
      { kind: "section", label: "Type of Notice" },
      {
        kind: "checkbox_group",
        key: "warning_type",
        options: [
          { key: "verbal", label: "Verbal" },
          { key: "written", label: "Written" },
          { key: "final", label: "Final" },
        ],
        responsibility: "ai",
        columns: 3,
      },
      { kind: "section", label: "What Happened" },
      {
        kind: "field",
        field: field("observation", "Observation", "ai", "long_text", {
          help: "What the manager observed, in the manager's own account.",
          narrative: "observed_expectation",
        }),
      },
      {
        kind: "field",
        field: field("policy_language", "Policy reference", "ai", "long_text", {
          help: "Quoted only from an approved knowledge-base document.",
          policyGrounded: true,
        }),
      },
      { kind: "field", field: field("prior_actions", "Previous notices for this issue", "ai") },
      { kind: "section", label: "Action Plan" },
      {
        kind: "field",
        field: field("action_plan", "Action Plan", "ai", "long_text", {
          narrative: "plan_of_action",
          requiredClosing: FIXTURE_REQUIRED_CLOSING,
        }),
      },
      {
        kind: "checkbox_group",
        key: "retraining_required",
        label: FIXTURE_YES_NO_QUESTION,
        options: [
          { key: "yes", label: "Yes" },
          { key: "no", label: "No" },
        ],
        responsibility: "manager",
        columns: 2,
        single: true,
      },
      {
        kind: "answer_statements",
        lines: [
          {
            label: "Retraining",
            parts: [
              {
                key: "retraining_required",
                statements: {
                  yes: "Retraining is required.",
                  no: "Retraining is not required.",
                },
              },
            ],
          },
        ],
      },
      { kind: "field", field: field("manager_notes", "Manager notes", "manager", "long_text") },
      { kind: "acknowledgement", text: "I confirm this notice was discussed with me." },
      { kind: "signature_row", label: "Employee Signature", dateLabel: "Date" },
      { kind: "signature_row", label: "Manager Signature", dateLabel: "Date" },
      {
        kind: "draft_details",
        label: "Draft Details (fixture reference sheet)",
        note: "Not part of the signed pages.",
        entries: [
          { label: "Observation", key: "observation" },
          { label: "Policy reference", key: "policy_language" },
        ],
      },
    ],
  };
}

export const FIXTURE_CORRECTIVE_SEED: TemplateSeed = {
  key: FIXTURE_CORRECTIVE_KEY,
  name: "Fixture Corrective Notice",
  shortName: "Corrective Notice",
  description: "TEST FIXTURE — a corrective notice for engine tests. Not a Buff City Soap form.",
  category: category("fixture-team"),
  layoutFamily: "corrective",
  requiredPermission: "create_forms",
  displayOrder: 11,
  document: fixtureCorrectiveDocument(),
  variants: [],
  revision: 3,
  revisionNote: "Fixture revision 3: the action plan carries its required closing.",
  bundledPdfName: "Fixture Corrective Notice.pdf",
};

/* ------------------------------------------------- Fixture Policy Review --- */

export const FIXTURE_POLICY_REVIEW_KEY = "fixture-policy-review";

export const FIXTURE_POLICY_REVIEW_SEED: TemplateSeed = {
  key: FIXTURE_POLICY_REVIEW_KEY,
  name: "Fixture Policy Review",
  shortName: "Policy Review",
  description: "TEST FIXTURE — a form whose NAME reads like a policy document.",
  category: category("fixture-team"),
  layoutFamily: "corrective",
  requiredPermission: "create_forms",
  displayOrder: 12,
  document: {
    paper: "letter",
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Policy Review" },
      ...header(),
      { kind: "section", label: "Policy" },
      {
        kind: "field",
        field: field("policy_violated", "Policy reviewed", "ai", "text", { policyGrounded: true }),
      },
      {
        kind: "field",
        field: field("policy_language", "Policy wording", "ai", "long_text", { policyGrounded: true }),
      },
      { kind: "signature_row", label: "Manager Signature", dateLabel: "Date" },
    ],
  },
  variants: [],
  revision: 1,
  revisionNote: "Fixture.",
  bundledPdfName: "Fixture Policy Review.pdf",
};

/* --------------------------------------------------- Fixture Role Review --- */

export const FIXTURE_ROLE_REVIEW_KEY = "fixture-role-review";

/** Two readings of one review document: {{role}} and {{roleAbbr}} resolve from these. */
export const FIXTURE_REVIEW_VARIANTS: FormVariant[] = [
  { key: "lead", label: "Store Lead review", role: "Store Lead", roleAbbr: "SL", reviewedPosition: "SL" },
  {
    key: "trainee",
    label: "Lead in Training review",
    role: "Lead in Training",
    roleAbbr: "LIT",
    reviewedPosition: "LIT",
  },
];

/** The trainee reading's own position description; never printed on a lead review. */
export const FIXTURE_TRAINEE_DESCRIPTION = "A Lead in Training is learning to run a shift.";

export function fixtureRoleReviewDocument(): FormDocument {
  return {
    paper: "letter",
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Role Review - {{roleAbbr}}" },
      ...header(),
      {
        kind: "reference",
        label: "Position Description",
        body: ["A Store Lead runs the shift and supports the {{role}} team."],
        variantKey: "lead",
      },
      {
        kind: "reference",
        label: "Position Description",
        body: [FIXTURE_TRAINEE_DESCRIPTION],
        variantKey: "trainee",
      },
      { kind: "section", label: "Self-Assessment" },
      { kind: "note", text: "This section is completed by hand, in the conversation." },
      {
        kind: "field",
        field: field(
          "self_succeeding",
          "In what areas do you feel you are succeeding as a {{roleAbbr}}?",
          "manual",
          "long_text",
        ),
      },
      {
        kind: "numbered_list",
        key: "self_strengths",
        label: "What are your overall top three strengths?",
        count: 3,
        responsibility: "manual",
      },
      { kind: "page_break" },
      { kind: "section", label: "Manager Review" },
      {
        kind: "expectation_checklist",
        successKey: "expectations_success",
        improvementKey: "expectations_improvement",
        label: "Standing expectations",
        legend: "Mark each expectation as an area of success or one needing improvement.",
        options: [
          { key: "opens_on_time", label: "Opens the store on time" },
          { key: "greets_guests", label: "Greets every guest" },
          { key: "keeps_shelves_full", label: "Keeps the shelves stocked and faced" },
        ],
        responsibility: "ai",
      },
      {
        kind: "numbered_list",
        key: "top_strengths",
        label: "Overall top three strengths",
        count: 3,
        responsibility: "ai",
      },
      {
        kind: "numbered_list",
        key: "improvement_areas",
        label: "Areas for improvement",
        count: 3,
        responsibility: "ai",
      },
      {
        kind: "objective_rows",
        label: "Objectives",
        planLabel: "Plan of Action",
        rows: [
          { key: "objective_bench", category: "Bench", objective: "Train one new opener." },
          { key: "objective_standards", category: "Store Standards", objective: "Pass the fixture walk." },
        ],
        responsibility: "ai",
      },
      {
        kind: "field",
        field: field("plan_of_action", "Plan of Action", "ai", "long_text"),
      },
      { kind: "acknowledgement", text: "Acknowledgement: I confirm this review was discussed with me." },
      { kind: "signature_row", label: "{{role}} Signature", dateLabel: "Date" },
      { kind: "page_break" },
      { kind: "section", label: "Follow-up" },
      { kind: "section", label: "Re-Evaluation" },
      { kind: "field", field: field("re_evaluation_notes", "Re-evaluation notes", "manager", "long_text") },
      { kind: "acknowledgement", text: "Acknowledgement of the re-evaluation meeting." },
      { kind: "signature_row", label: "Manager Signature", dateLabel: "Date" },
    ],
  };
}

export const FIXTURE_ROLE_REVIEW_SEED: TemplateSeed = {
  key: FIXTURE_ROLE_REVIEW_KEY,
  name: "Fixture Role Review",
  shortName: "Role Review",
  description: "TEST FIXTURE — one review document read two ways. Not a Buff City Soap form.",
  category: category("fixture-team"),
  layoutFamily: "review",
  requiredPermission: "create_forms",
  displayOrder: 13,
  document: fixtureRoleReviewDocument(),
  variants: FIXTURE_REVIEW_VARIANTS,
  revision: 2,
  revisionNote: "Fixture revision 2: the readings were renamed.",
  bundledPdfName: "Fixture Role Review.pdf",
};

/* --------------------------------------------------- Fixture Peer Review --- */

export const FIXTURE_PEER_REVIEW_KEY = "fixture-peer-review";

/**
 * The same kind of self-review question as the role review's — and on THIS
 * template the assistant drafts it. Responsibility is per template.
 */
export const FIXTURE_PEER_REVIEW_SEED: TemplateSeed = {
  key: FIXTURE_PEER_REVIEW_KEY,
  name: "Fixture Peer Review",
  shortName: "Peer Review",
  description: "TEST FIXTURE — a review whose self-review the assistant drafts.",
  category: category("fixture-team"),
  layoutFamily: "review",
  requiredPermission: "create_forms",
  displayOrder: 14,
  document: {
    paper: "letter",
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Peer Review - {{roleAbbr}}" },
      ...header(),
      { kind: "section", label: "Self Review" },
      {
        kind: "field",
        field: field("employee_self_review", "Team member's thoughts", "ai", "long_text"),
      },
      {
        kind: "numbered_list",
        key: "top_strengths",
        label: "Overall top three strengths",
        count: 3,
        responsibility: "ai",
      },
      { kind: "signature_row", label: "Team Member Signature", dateLabel: "Date" },
    ],
  },
  variants: [{ key: "default", label: "Peer review", role: "Team Member", roleAbbr: "TM" }],
  revision: 1,
  revisionNote: "Fixture.",
  bundledPdfName: "Fixture Peer Review.pdf",
};

/* ----------------------------------------------- Fixture Follow-Up Note --- */

export const FIXTURE_FOLLOW_UP_KEY = "fixture-follow-up";

export const FIXTURE_FOLLOW_UP_SEED: TemplateSeed = {
  key: FIXTURE_FOLLOW_UP_KEY,
  name: "Fixture Follow-Up Note",
  shortName: "Follow-Up Note",
  description: "TEST FIXTURE — a form defined by a knowledge-base framework, with no paper source.",
  category: category("fixture-team"),
  layoutFamily: "coaching",
  requiredPermission: "create_forms",
  displayOrder: 15,
  provenance: {
    kind: "framework",
    document: "FIXTURE_FRAMEWORK",
    locator: "§1 Fixture follow-up template",
    note: "Fixture provenance: this test form did NOT originate from an uploaded business PDF.",
  },
  document: {
    paper: "letter",
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Follow-Up Note" },
      {
        kind: "field",
        field: field("follow_up_summary", "Summary", "ai", "long_text"),
      },
      {
        kind: "field",
        field: field("next_follow_up", "Next Follow-Up", "ai", "text", {
          semantics: "follow_up_timeframe",
        }),
      },
    ],
  },
  variants: [],
  revision: 1,
  revisionNote: "Framework-defined fixture.",
  bundledPdfName: "Fixture Follow-Up Note.pdf",
};

/* ------------------------------------------------- Fixture Separation --- */

export const FIXTURE_SEPARATION_KEY = "fixture-separation";

/** A form behind a permission a store-level manager does not hold. */
export const FIXTURE_RESTRICTED_PERMISSION = "manage_form_records";

export const FIXTURE_SEPARATION_SEED: TemplateSeed = {
  key: FIXTURE_SEPARATION_KEY,
  name: "Fixture Separation Record",
  shortName: "Separation Record",
  description: "TEST FIXTURE — a separation record behind its own permission.",
  category: category("fixture-separation"),
  layoutFamily: "separation",
  requiredPermission: FIXTURE_RESTRICTED_PERMISSION,
  displayOrder: 16,
  document: {
    paper: "letter",
    style: { dateFormat: "us" },
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Separation Record" },
      ...header(),
      { kind: "field", field: field("last_day_worked", "Last day worked", "manager", "date") },
      {
        kind: "checkbox_group",
        key: "items_returned",
        label: "All store items were returned",
        options: [
          { key: "yes", label: "Yes" },
          { key: "no", label: "No" },
        ],
        responsibility: "manager",
        columns: 2,
        single: true,
      },
      {
        kind: "checkbox_group",
        key: "eligible_for_rehire",
        label: "Is this team member eligible for rehire?",
        options: [
          { key: "yes", label: "Yes" },
          { key: "no", label: "No" },
        ],
        responsibility: "manager",
        columns: 2,
        single: true,
      },
      {
        kind: "answer_statements",
        lines: [
          {
            label: "Details",
            parts: [
              { key: "items_returned", statements: { yes: "Store items were returned.", no: "Store items were not returned." } },
              { key: "eligible_for_rehire", statements: { yes: "Eligible for rehire.", no: "Not eligible for rehire." } },
            ],
          },
        ],
      },
      { kind: "signature_row", label: "Manager Signature", dateLabel: "Date" },
    ],
  },
  variants: [],
  revision: 1,
  revisionNote: "Fixture.",
  bundledPdfName: "Fixture Separation Record.pdf",
};

/* --------------------------------------------------- Fixture Interview --- */

export const FIXTURE_INTERVIEW_KEY = "fixture-interview";

export const FIXTURE_INTERVIEW_SEED: TemplateSeed = {
  key: FIXTURE_INTERVIEW_KEY,
  name: "Fixture Interview Guide",
  shortName: "Interview Guide",
  description: "TEST FIXTURE — an interview guide.",
  category: category("fixture-hiring"),
  layoutFamily: "interview",
  requiredPermission: "create_forms",
  displayOrder: 17,
  document: {
    paper: "letter",
    blocks: [
      { kind: "letterhead", brand: BRAND, title: "Fixture Interview Guide" },
      {
        kind: "field_row",
        fields: [
          field("employee_name", "Applicant Name", "system"),
          field("form_date", "Date", "system", "date"),
        ],
      },
      {
        kind: "checkbox_group",
        key: "of_working_age",
        label: "Is the applicant of working age?",
        options: [
          { key: "yes", label: "Yes" },
          { key: "no", label: "No" },
        ],
        responsibility: "manager",
        columns: 2,
        single: true,
      },
      { kind: "field", field: field("interview_notes", "Interview notes", "manager", "long_text") },
      {
        kind: "checkbox_group",
        key: "recommendation",
        label: "Final Recommendation",
        options: [
          { key: "hire", label: "Hire" },
          { key: "no_hire", label: "No Hire" },
        ],
        responsibility: "manager",
        columns: 2,
      },
      { kind: "signature_row", label: "Interviewer Signature", dateLabel: "Date" },
    ],
  },
  variants: [],
  revision: 1,
  revisionNote: "Fixture.",
  bundledPdfName: "Fixture Interview Guide.pdf",
};

/* --------------------------------------------------------- the registry --- */

const entry = (
  seed: TemplateSeed,
  intentPhrases: string[],
  overrides: Partial<Omit<CompanyFormDefinition, "seed" | "intentPhrases">> = {},
): CompanyFormDefinition => ({
  seed,
  intentPhrases,
  inlineDraft: true,
  offeredInChooser: true,
  checkEmployeeName: true,
  revisable: true,
  chatCorrectableFields: ["employee_name", "form_date"],
  clarifyOn: null,
  status: "placeholder",
  ...overrides,
});

/**
 * The fixture registry, in the order a library lists it. The shipped example
 * stays in it, so a test against the fixtures still sees the real entry.
 */
export const FIXTURE_COMPANY_FORMS: readonly CompanyFormDefinition[] = [
  entry(FIXTURE_COACHING_SEED, ["coaching note", "coaching form", "coaching"], {
    clarifyOn: { verb: "coach", noun: "coaching" },
  }),
  entry(FIXTURE_CORRECTIVE_SEED, ["corrective notice", "corrective action", "written warning", "verbal warning"]),
  entry(FIXTURE_POLICY_REVIEW_SEED, ["policy review form"], { inlineDraft: false }),
  entry(FIXTURE_ROLE_REVIEW_SEED, ["role review"], { revisable: false }),
  entry(FIXTURE_PEER_REVIEW_SEED, ["peer review"], { inlineDraft: false }),
  entry(FIXTURE_FOLLOW_UP_SEED, ["follow-up note", "follow up note"]),
  entry(FIXTURE_SEPARATION_SEED, ["separation record", "separation form"], { checkEmployeeName: false }),
  /* Published, but WITHHELD from what Bubbles offers: not in the chooser. */
  entry(FIXTURE_INTERVIEW_SEED, ["interview guide"], {
    inlineDraft: false,
    offeredInChooser: false,
    checkEmployeeName: false,
    revisable: false,
  }),
  entry(EXAMPLE_CHECK_IN_SEED, ["check-in form", "check in form", "example check-in"]),
];

export const FIXTURE_TEMPLATE_SEEDS: readonly TemplateSeed[] = FIXTURE_COMPANY_FORMS.map(
  (definition) => definition.seed,
);

export function fixtureSeed(key: string): TemplateSeed {
  const found = FIXTURE_TEMPLATE_SEEDS.find((seed) => seed.key === key);
  if (!found) throw new Error(`no fixture seed ${key}`);
  return found;
}

/** The shape of `@/config/company/forms`, filled with the fixture registry. */
export function fixtureFormsModule() {
  return {
    COMPANY_FORMS: FIXTURE_COMPANY_FORMS,
    COMPANY_FORM_CATEGORIES: FIXTURE_FORM_CATEGORIES,
    PRIMARY_FORM_KEY: null as string | null,
    companyFormFor: (key: string) => FIXTURE_COMPANY_FORMS.find((definition) => definition.seed.key === key),
  };
}
